### ISSUE TITLE
Access current state from watcher

### ISSUE THREAD

**Issue by peter-brennan** [Gumball12/pinia-plugin-watch#4]
@Gumball12 

I am watching a Boolean in the state and if it is false I want to update the value of another state variable but this is not defined. How would i access the current stores state from a watcher?

i've tried the following:

```
watch: {
    showOptions(showOptions) {
        if (!showOptions) {
            this.sendEmail = false
        }
    }
}
```
and
```
watch: {
    showOptions: (showOptions) => {
        if (!showOptions) {
            this.sendEmail = false
        }
    }
}
```

**Comment by peter-brennan** [comment]
Ok i figured it out, from within the watch i have to use the store. Would be handy though to have "this" store exposed.

```
watch: {
    showOptions: (showOptions) => {
        if (!showOptions) {
            const store = useStore()
            store.sendEmail = false
        }
    }
}
```

**Comment by Gumball12** [comment]
@peter-brennan 
Thanks for the great suggestion. It would be more convenient to be able to reference this from within the watcher as you mentioned. I'll add that in the next update. Thank you!

**Comment by Gumball12** [comment]
@peter-brennan 
Sorry for the late. You can now access the Store object as below:

```ts
watch: {
  showOptions: (showOptions, oldValue, onCleanup, store) => {
    if (!showOptions) {
      store.sendEmail = false
    }
  }
}
```

Along with this, the onCleanup function has also been provided. This was implemented to fully emulate the behavior of the original [Vue `watch()`](https://vuejs.org/api/reactivity-core.html#watch).

**Comment by Gumball12** [comment]
@peter-brennan 

See [usage](https://github.com/Gumball12/pinia-plugin-watch/blob/main/USAGE.md#accessing-the-original-store-object) for related documentation. Thank you!

**Comment by peter-brennan** [comment]
> @peter-brennan
> 
> See [usage](https://github.com/Gumball12/pinia-plugin-watch/blob/main/USAGE.md#accessing-the-original-store-object) for related documentation. Thank you!

Great work mate, thank you!
